name: 'PushPlus' 
description: 'send message to push+'
inputs:
  token:
    description: 'push+ token'
    required: true
  title:
    description: 'message title'
    required: true
  content:
    description: 'message content'
    required: true
  template:
    description: 'message template: html/json'
    required: false
    default: 'html'

runs:
  using: 'composite'
  steps:
    - run: curl "http://pushplus.hxtrip.com/send" -H "Content-Type: application/json" -d "{\"token\":\"${{ inputs.token }}\",\"title\":\"${{ inputs.title }}\",\"content\":\"${{ inputs.content }}\",\"template\":\"${{ inputs.template }}\"}" -X POST
      shell: bash
